// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: my.proto

package proc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServClient is the client API for Serv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServClient interface {
	// определение метода с использованием rpc.
	GetData(ctx context.Context, in *Point, opts ...grpc.CallOption) (*Point, error)
}

type servClient struct {
	cc grpc.ClientConnInterface
}

func NewServClient(cc grpc.ClientConnInterface) ServClient {
	return &servClient{cc}
}

func (c *servClient) GetData(ctx context.Context, in *Point, opts ...grpc.CallOption) (*Point, error) {
	out := new(Point)
	err := c.cc.Invoke(ctx, "/Serv/GetData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServServer is the server API for Serv service.
// All implementations must embed UnimplementedServServer
// for forward compatibility
type ServServer interface {
	// определение метода с использованием rpc.
	GetData(context.Context, *Point) (*Point, error)
	mustEmbedUnimplementedServServer()
}

// UnimplementedServServer must be embedded to have forward compatible implementations.
type UnimplementedServServer struct {
}

func (UnimplementedServServer) GetData(context.Context, *Point) (*Point, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetData not implemented")
}
func (UnimplementedServServer) mustEmbedUnimplementedServServer() {}

// UnsafeServServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServServer will
// result in compilation errors.
type UnsafeServServer interface {
	mustEmbedUnimplementedServServer()
}

func RegisterServServer(s grpc.ServiceRegistrar, srv ServServer) {
	s.RegisterService(&Serv_ServiceDesc, srv)
}

func _Serv_GetData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Point)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServServer).GetData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Serv/GetData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServServer).GetData(ctx, req.(*Point))
	}
	return interceptor(ctx, in, info, handler)
}

// Serv_ServiceDesc is the grpc.ServiceDesc for Serv service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Serv_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Serv",
	HandlerType: (*ServServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetData",
			Handler:    _Serv_GetData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "my.proto",
}
